/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSonhosRouteImport } from './routes/_app.sonhos'
import { Route as AppResumoRouteImport } from './routes/_app.resumo'
import { Route as AppNotasRouteImport } from './routes/_app.notas'
import { Route as AppLancamentosRouteImport } from './routes/_app.lancamentos'
import { Route as AppCasalRouteImport } from './routes/_app.casal'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSonhosRoute = AppSonhosRouteImport.update({
  id: '/sonhos',
  path: '/sonhos',
  getParentRoute: () => AppRoute,
} as any)
const AppResumoRoute = AppResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppLancamentosRoute = AppLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppCasalRoute = AppCasalRouteImport.update({
  id: '/casal',
  path: '/casal',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRoute
  '/casal': typeof AppCasalRoute
  '/lancamentos': typeof AppLancamentosRoute
  '/notas': typeof AppNotasRoute
  '/resumo': typeof AppResumoRoute
  '/sonhos': typeof AppSonhosRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/casal': typeof AppCasalRoute
  '/lancamentos': typeof AppLancamentosRoute
  '/notas': typeof AppNotasRoute
  '/resumo': typeof AppResumoRoute
  '/sonhos': typeof AppSonhosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/_app/casal': typeof AppCasalRoute
  '/_app/lancamentos': typeof AppLancamentosRoute
  '/_app/notas': typeof AppNotasRoute
  '/_app/resumo': typeof AppResumoRoute
  '/_app/sonhos': typeof AppSonhosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/casal'
    | '/lancamentos'
    | '/notas'
    | '/resumo'
    | '/sonhos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/casal'
    | '/lancamentos'
    | '/notas'
    | '/resumo'
    | '/sonhos'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/casal'
    | '/_app/lancamentos'
    | '/_app/notas'
    | '/_app/resumo'
    | '/_app/sonhos'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sonhos': {
      id: '/_app/sonhos'
      path: '/sonhos'
      fullPath: '/sonhos'
      preLoaderRoute: typeof AppSonhosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumo': {
      id: '/_app/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof AppResumoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notas': {
      id: '/_app/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lancamentos': {
      id: '/_app/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AppLancamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/casal': {
      id: '/_app/casal'
      path: '/casal'
      fullPath: '/casal'
      preLoaderRoute: typeof AppCasalRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCasalRoute: typeof AppCasalRoute
  AppLancamentosRoute: typeof AppLancamentosRoute
  AppNotasRoute: typeof AppNotasRoute
  AppResumoRoute: typeof AppResumoRoute
  AppSonhosRoute: typeof AppSonhosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasalRoute: AppCasalRoute,
  AppLancamentosRoute: AppLancamentosRoute,
  AppNotasRoute: AppNotasRoute,
  AppResumoRoute: AppResumoRoute,
  AppSonhosRoute: AppSonhosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
